application: appogee-bookmarks
version: images
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /.*
  script: main.application
  
libraries:
- name: webapp2
  version: 2.5.2
- name: PIL
  version: latest
- name: jinja2
  version: latest